"""crear modelos iniciales

Revision ID: 029d6f43f577
Revises: 
Create Date: 2026-09-20 21:00:07.480008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029d6f43f577'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('registro_profesional', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.create_index(op.f('ix_medicos_registro_profesional'), 'medicos', ['registro_profesional'], unique=True)
    op.create_index(op.f('ix_medicos_usuario_id'), 'medicos', ['usuario_id'], unique=True)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_usuario_id'), 'pacientes', ['usuario_id'], unique=True)
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'confirmada', 'cancelada')", name='ck_cita_estado'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'fecha', 'hora', name='uq_cita_medico_fecha_hora'),
    sa.UniqueConstraint('paciente_id', 'fecha', 'hora', name='uq_cita_paciente_fecha_hora')
    )
    op.create_index(op.f('ix_citas_fecha'), 'citas', ['fecha'], unique=False)
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_index(op.f('ix_citas_medico_id'), 'citas', ['medico_id'], unique=False)
    op.create_index(op.f('ix_citas_paciente_id'), 'citas', ['paciente_id'], unique=False)
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 0 AND 6', name='ck_disponibilidad_dia_semana'),
    sa.CheckConstraint('hora_inicio < hora_fin', name='ck_disponibilidad_horas'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'dia_semana', 'hora_inicio', 'hora_fin', name='uq_disponibilidad_medico_horario')
    )
    op.create_index(op.f('ix_disponibilidades_id'), 'disponibilidades', ['id'], unique=False)
    op.create_index(op.f('ix_disponibilidades_medico_id'), 'disponibilidades', ['medico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disponibilidades_medico_id'), table_name='disponibilidades')
    op.drop_index(op.f('ix_disponibilidades_id'), table_name='disponibilidades')
    op.drop_table('disponibilidades')
    op.drop_index(op.f('ix_citas_paciente_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_medico_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_fecha'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_pacientes_usuario_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_medicos_usuario_id'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_registro_profesional'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
